### ISSUE TITLE
MacOS Catalina: Out of Memory Error

### ISSUE THREAD

**Issue by harishperfect** [juancarlospaco/faster-than-walk#1]
Just importing the package causes the error to appear.

In Python Console, (I was on Python 3.7.4)
```
>>> import faster_than_walk as ftw
out of memory
```
 - OS: MacOS Catalina 
 - Version 10.15

**Comment by juancarlospaco** [comment]
Clone the repo and compile it.
here is shown how, different project but same process: https://github.com/juancarlospaco/faster-than-requests#windows

**Comment by evertrol** [comment]
The README just mentions to use `pip install faster_than_walk` for installation.
Perhaps it should be noted that this doesn't work for MacOS (Mojave in my case, Catalina in the OP's case), with further instructions.
